### PR TITLE
Rename users seeder class name

### PR DESCRIPTION
**Pull request by flyingluscas**
There was a bug when seeding the users table, the users seeder class was renamed to fix that.

### CODE REVIEW

**Comment by hernandev** [comment]
Thanks

**Comment by hernandev** [comment]
Other seeders needs to be built, right now it's just this one working.

This app needs to move to a more easy to install solution, and I'm coding for this from now.

Thanks for the help.

Creating seeders for other models are appreaciated right now.

**Comment by flyingluscas** [comment]
Right @hernandev,  i will see what i can do :)

**Comment by hernandev** [comment]
many thanks

**Pull request merged**
